// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package e2e

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	painters "marwan.io/protoc-gen-twirpql/e2e/painters"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrafficLight int32

const (
	TrafficLight_RED    TrafficLight = 0
	TrafficLight_YELLOW TrafficLight = 1
	TrafficLight_GREEN  TrafficLight = 2
)

var TrafficLight_name = map[int32]string{
	0: "RED",
	1: "YELLOW",
	2: "GREEN",
}

var TrafficLight_value = map[string]int32{
	"RED":    0,
	"YELLOW": 1,
	"GREEN":  2,
}

func (x TrafficLight) String() string {
	return proto.EnumName(TrafficLight_name, int32(x))
}

func (TrafficLight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResp struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

func (m *HelloResp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type TrafficJamReq struct {
	Color                TrafficLight `protobuf:"varint,1,opt,name=color,proto3,enum=e2e.TrafficLight" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrafficJamReq) Reset()         { *m = TrafficJamReq{} }
func (m *TrafficJamReq) String() string { return proto.CompactTextString(m) }
func (*TrafficJamReq) ProtoMessage()    {}
func (*TrafficJamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *TrafficJamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficJamReq.Unmarshal(m, b)
}
func (m *TrafficJamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficJamReq.Marshal(b, m, deterministic)
}
func (m *TrafficJamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficJamReq.Merge(m, src)
}
func (m *TrafficJamReq) XXX_Size() int {
	return xxx_messageInfo_TrafficJamReq.Size(m)
}
func (m *TrafficJamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficJamReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficJamReq proto.InternalMessageInfo

func (m *TrafficJamReq) GetColor() TrafficLight {
	if m != nil {
		return m.Color
	}
	return TrafficLight_RED
}

type TrafficJamResp struct {
	Next                 TrafficLight `protobuf:"varint,1,opt,name=next,proto3,enum=e2e.TrafficLight" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrafficJamResp) Reset()         { *m = TrafficJamResp{} }
func (m *TrafficJamResp) String() string { return proto.CompactTextString(m) }
func (*TrafficJamResp) ProtoMessage()    {}
func (*TrafficJamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *TrafficJamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficJamResp.Unmarshal(m, b)
}
func (m *TrafficJamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficJamResp.Marshal(b, m, deterministic)
}
func (m *TrafficJamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficJamResp.Merge(m, src)
}
func (m *TrafficJamResp) XXX_Size() int {
	return xxx_messageInfo_TrafficJamResp.Size(m)
}
func (m *TrafficJamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficJamResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficJamResp proto.InternalMessageInfo

func (m *TrafficJamResp) GetNext() TrafficLight {
	if m != nil {
		return m.Next
	}
	return TrafficLight_RED
}

type PaintersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaintersReq) Reset()         { *m = PaintersReq{} }
func (m *PaintersReq) String() string { return proto.CompactTextString(m) }
func (*PaintersReq) ProtoMessage()    {}
func (*PaintersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *PaintersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaintersReq.Unmarshal(m, b)
}
func (m *PaintersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaintersReq.Marshal(b, m, deterministic)
}
func (m *PaintersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaintersReq.Merge(m, src)
}
func (m *PaintersReq) XXX_Size() int {
	return xxx_messageInfo_PaintersReq.Size(m)
}
func (m *PaintersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaintersReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaintersReq proto.InternalMessageInfo

type PaintersResp struct {
	BestPainter          *painters.Painter `protobuf:"bytes,1,opt,name=bestPainter,proto3" json:"bestPainter,omitempty"`
	AllPainters          []string          `protobuf:"bytes,2,rep,name=allPainters,proto3" json:"allPainters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaintersResp) Reset()         { *m = PaintersResp{} }
func (m *PaintersResp) String() string { return proto.CompactTextString(m) }
func (*PaintersResp) ProtoMessage()    {}
func (*PaintersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *PaintersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaintersResp.Unmarshal(m, b)
}
func (m *PaintersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaintersResp.Marshal(b, m, deterministic)
}
func (m *PaintersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaintersResp.Merge(m, src)
}
func (m *PaintersResp) XXX_Size() int {
	return xxx_messageInfo_PaintersResp.Size(m)
}
func (m *PaintersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PaintersResp.DiscardUnknown(m)
}

var xxx_messageInfo_PaintersResp proto.InternalMessageInfo

func (m *PaintersResp) GetBestPainter() *painters.Painter {
	if m != nil {
		return m.BestPainter
	}
	return nil
}

func (m *PaintersResp) GetAllPainters() []string {
	if m != nil {
		return m.AllPainters
	}
	return nil
}

type TranslateResp struct {
	Translations         map[string]*Word `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TranslateResp) Reset()         { *m = TranslateResp{} }
func (m *TranslateResp) String() string { return proto.CompactTextString(m) }
func (*TranslateResp) ProtoMessage()    {}
func (*TranslateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *TranslateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateResp.Unmarshal(m, b)
}
func (m *TranslateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateResp.Marshal(b, m, deterministic)
}
func (m *TranslateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateResp.Merge(m, src)
}
func (m *TranslateResp) XXX_Size() int {
	return xxx_messageInfo_TranslateResp.Size(m)
}
func (m *TranslateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateResp.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateResp proto.InternalMessageInfo

func (m *TranslateResp) GetTranslations() map[string]*Word {
	if m != nil {
		return m.Translations
	}
	return nil
}

type Word struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Word) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type TranslateReq struct {
	Words                map[string]*Word `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TranslateReq) Reset()         { *m = TranslateReq{} }
func (m *TranslateReq) String() string { return proto.CompactTextString(m) }
func (*TranslateReq) ProtoMessage()    {}
func (*TranslateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *TranslateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateReq.Unmarshal(m, b)
}
func (m *TranslateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateReq.Marshal(b, m, deterministic)
}
func (m *TranslateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateReq.Merge(m, src)
}
func (m *TranslateReq) XXX_Size() int {
	return xxx_messageInfo_TranslateReq.Size(m)
}
func (m *TranslateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateReq.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateReq proto.InternalMessageInfo

func (m *TranslateReq) GetWords() map[string]*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

type BreadReq struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreadReq) Reset()         { *m = BreadReq{} }
func (m *BreadReq) String() string { return proto.CompactTextString(m) }
func (*BreadReq) ProtoMessage()    {}
func (*BreadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *BreadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreadReq.Unmarshal(m, b)
}
func (m *BreadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreadReq.Marshal(b, m, deterministic)
}
func (m *BreadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreadReq.Merge(m, src)
}
func (m *BreadReq) XXX_Size() int {
	return xxx_messageInfo_BreadReq.Size(m)
}
func (m *BreadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BreadReq.DiscardUnknown(m)
}

var xxx_messageInfo_BreadReq proto.InternalMessageInfo

func (m *BreadReq) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BreadResp struct {
	// Types that are valid to be assigned to Answer:
	//	*BreadResp_Name
	//	*BreadResp_Toasted
	Answer               isBreadResp_Answer `protobuf_oneof:"answer"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BreadResp) Reset()         { *m = BreadResp{} }
func (m *BreadResp) String() string { return proto.CompactTextString(m) }
func (*BreadResp) ProtoMessage()    {}
func (*BreadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *BreadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreadResp.Unmarshal(m, b)
}
func (m *BreadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreadResp.Marshal(b, m, deterministic)
}
func (m *BreadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreadResp.Merge(m, src)
}
func (m *BreadResp) XXX_Size() int {
	return xxx_messageInfo_BreadResp.Size(m)
}
func (m *BreadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BreadResp.DiscardUnknown(m)
}

var xxx_messageInfo_BreadResp proto.InternalMessageInfo

type isBreadResp_Answer interface {
	isBreadResp_Answer()
}

type BreadResp_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type BreadResp_Toasted struct {
	Toasted bool `protobuf:"varint,2,opt,name=toasted,proto3,oneof"`
}

func (*BreadResp_Name) isBreadResp_Answer() {}

func (*BreadResp_Toasted) isBreadResp_Answer() {}

func (m *BreadResp) GetAnswer() isBreadResp_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (m *BreadResp) GetName() string {
	if x, ok := m.GetAnswer().(*BreadResp_Name); ok {
		return x.Name
	}
	return ""
}

func (m *BreadResp) GetToasted() bool {
	if x, ok := m.GetAnswer().(*BreadResp_Toasted); ok {
		return x.Toasted
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BreadResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BreadResp_Name)(nil),
		(*BreadResp_Toasted)(nil),
	}
}

func init() {
	proto.RegisterEnum("e2e.TrafficLight", TrafficLight_name, TrafficLight_value)
	proto.RegisterType((*HelloReq)(nil), "e2e.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "e2e.HelloResp")
	proto.RegisterType((*TrafficJamReq)(nil), "e2e.TrafficJamReq")
	proto.RegisterType((*TrafficJamResp)(nil), "e2e.TrafficJamResp")
	proto.RegisterType((*PaintersReq)(nil), "e2e.PaintersReq")
	proto.RegisterType((*PaintersResp)(nil), "e2e.PaintersResp")
	proto.RegisterType((*TranslateResp)(nil), "e2e.TranslateResp")
	proto.RegisterMapType((map[string]*Word)(nil), "e2e.TranslateResp.TranslationsEntry")
	proto.RegisterType((*Word)(nil), "e2e.Word")
	proto.RegisterType((*TranslateReq)(nil), "e2e.TranslateReq")
	proto.RegisterMapType((map[string]*Word)(nil), "e2e.TranslateReq.WordsEntry")
	proto.RegisterType((*BreadReq)(nil), "e2e.BreadReq")
	proto.RegisterType((*BreadResp)(nil), "e2e.BreadResp")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x9a, 0xa6, 0x6d, 0x6e, 0xda, 0xaa, 0xbd, 0x4c, 0xa2, 0x8a, 0x10, 0xab, 0x22, 0x3e,
	0x2a, 0x1e, 0x8a, 0x94, 0x09, 0x98, 0x78, 0x2c, 0x54, 0xad, 0xa6, 0x0a, 0x90, 0x41, 0x9a, 0xe0,
	0xcd, 0x6b, 0xbd, 0x12, 0x91, 0x25, 0x69, 0xec, 0x6e, 0xec, 0x17, 0xf0, 0x4b, 0xf8, 0x8f, 0x3c,
	0x22, 0x3b, 0x76, 0x1a, 0x56, 0x9e, 0xf6, 0x76, 0xef, 0xb9, 0xe7, 0x5e, 0xfb, 0xd8, 0xc7, 0x86,
	0x2e, 0x67, 0xf9, 0x75, 0xb4, 0x62, 0x93, 0x2c, 0x4f, 0x45, 0x8a, 0x36, 0x0b, 0x99, 0xff, 0x30,
	0xa3, 0x51, 0x22, 0x58, 0xce, 0x5f, 0x9a, 0xa0, 0xa8, 0x06, 0x8f, 0xa1, 0xbd, 0x60, 0x71, 0x9c,
	0x12, 0xb6, 0x45, 0x84, 0x46, 0x42, 0xaf, 0xd8, 0xd0, 0x1a, 0x59, 0x63, 0x97, 0xa8, 0x38, 0x38,
	0x06, 0x57, 0xd7, 0x79, 0x26, 0x09, 0x82, 0xfd, 0x14, 0x86, 0x20, 0xe3, 0xe0, 0x14, 0xba, 0x5f,
	0x72, 0x7a, 0x79, 0x19, 0xad, 0xce, 0xe8, 0x95, 0x9c, 0xf2, 0x1c, 0x9c, 0x55, 0x1a, 0xa7, 0xb9,
	0x62, 0xf5, 0xc2, 0xc1, 0x84, 0x85, 0x6c, 0xa2, 0x29, 0xcb, 0x68, 0xf3, 0x5d, 0x90, 0xa2, 0x1e,
	0xbc, 0x81, 0x5e, 0xb5, 0x93, 0x67, 0xf8, 0x14, 0x1a, 0x89, 0x99, 0xff, 0xdf, 0x4e, 0x55, 0x0e,
	0xba, 0xe0, 0x7d, 0xd2, 0x2a, 0x08, 0xdb, 0x06, 0x0c, 0x3a, 0xfb, 0x94, 0x67, 0x78, 0x02, 0xde,
	0x05, 0xe3, 0x42, 0x63, 0x6a, 0x98, 0x17, 0x0e, 0x26, 0xa5, 0x70, 0x5d, 0x20, 0x55, 0x16, 0x8e,
	0xc0, 0xa3, 0x71, 0x6c, 0xe6, 0x0c, 0xeb, 0x23, 0x7b, 0xec, 0x92, 0x2a, 0x14, 0xfc, 0xb6, 0x94,
	0xd2, 0x84, 0xc7, 0x54, 0x30, 0xb5, 0xd0, 0x02, 0x3a, 0x42, 0x03, 0x51, 0x9a, 0xf0, 0xa1, 0x35,
	0xb2, 0xc7, 0x5e, 0xf8, 0xc4, 0x6c, 0x7b, 0xcf, 0x2c, 0x33, 0x49, 0x9b, 0x25, 0x22, 0xbf, 0x25,
	0xff, 0x74, 0xfa, 0x67, 0x30, 0x38, 0xa0, 0x60, 0x1f, 0xec, 0x1f, 0xec, 0x56, 0x1f, 0xb6, 0x0c,
	0xf1, 0x18, 0x9c, 0x6b, 0x1a, 0xef, 0xd8, 0xb0, 0xae, 0x34, 0xb9, 0x6a, 0xa5, 0xf3, 0x34, 0x5f,
	0x93, 0x02, 0x7f, 0x5b, 0x3f, 0xb5, 0x82, 0xd7, 0xd0, 0x90, 0x90, 0xbc, 0xac, 0x9b, 0x34, 0x5f,
	0x9b, 0xcb, 0x92, 0x31, 0xfa, 0xd0, 0x8e, 0x69, 0xb2, 0xd9, 0xd1, 0x4d, 0x31, 0xc3, 0x25, 0x65,
	0x1e, 0xfc, 0xb2, 0xa0, 0x53, 0xd9, 0xf5, 0x16, 0x43, 0x70, 0x64, 0x93, 0xd1, 0xf5, 0xe8, 0xae,
	0xae, 0xad, 0x5a, 0x5a, 0xeb, 0x29, 0xa8, 0xfe, 0x3b, 0x80, 0x3d, 0x78, 0x5f, 0x05, 0x23, 0x68,
	0x4f, 0x73, 0x46, 0xd7, 0x72, 0x13, 0x47, 0xd2, 0x4d, 0xbb, 0xa4, 0xf0, 0x84, 0x4d, 0x8a, 0x24,
	0x98, 0x83, 0xab, 0x19, 0x3c, 0xc3, 0xa3, 0xaa, 0x6d, 0x17, 0xb5, 0xc2, 0xb8, 0xe8, 0x43, 0x4b,
	0xa4, 0x94, 0x0b, 0xb6, 0x56, 0x6b, 0xb5, 0x17, 0x35, 0x62, 0x80, 0x69, 0x1b, 0x9a, 0x34, 0xe1,
	0x37, 0x2c, 0x7f, 0x31, 0x51, 0x9a, 0x4b, 0x83, 0x61, 0x0b, 0x6c, 0x32, 0x7b, 0xdf, 0xaf, 0x21,
	0x40, 0xf3, 0xeb, 0x6c, 0xb9, 0xfc, 0x78, 0xde, 0xb7, 0xd0, 0x05, 0x67, 0x4e, 0x66, 0xb3, 0x0f,
	0xfd, 0x7a, 0xf8, 0xc7, 0x82, 0xd6, 0xe7, 0xe2, 0x79, 0xe1, 0x33, 0x70, 0xd4, 0xd3, 0xc0, 0xae,
	0x52, 0x61, 0x9e, 0x91, 0xdf, 0xab, 0xa6, 0x3c, 0xc3, 0x57, 0x00, 0x7b, 0x9f, 0x23, 0x56, 0x5d,
	0x5d, 0x3c, 0x19, 0xff, 0xc1, 0x01, 0xc6, 0x33, 0x0c, 0xc1, 0x9b, 0x33, 0xe3, 0x4f, 0x8e, 0x7d,
	0xc5, 0xa9, 0xf8, 0xde, 0x1f, 0xdc, 0x41, 0x54, 0x8f, 0x5b, 0x5e, 0x10, 0x0e, 0x0e, 0x2e, 0xcc,
	0xc7, 0x43, 0x6f, 0x4a, 0x19, 0xea, 0x2c, 0xb5, 0x0c, 0x73, 0xf2, 0x5a, 0x46, 0x79, 0xcc, 0x53,
	0xe7, 0x9b, 0xfc, 0x49, 0x2e, 0x9a, 0xea, 0xdf, 0x38, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x84,
	0x9e, 0x46, 0x0c, 0x66, 0x04, 0x00, 0x00,
}
