package twirpql

import (
	"context"

	"marwan.io/protoc-gen-twirpql/e2e"
)

// THIS CODE IS AUTOGENERATED BY TWIRPQL. DO NOT EDIT.

type Resolver struct {
	e2e.Service
}

func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}
func (r *Resolver) TranslateResp() TranslateRespResolver {
	return &translateRespResolver{r}
}

type queryResolver struct{ *Resolver }

func (r *queryResolver) Hello(ctx context.Context, req *e2e.HelloReq) (*e2e.HelloResp, error) {
	return r.Service.Hello(ctx, req)
}

func (r *queryResolver) TrafficJam(ctx context.Context, req *e2e.TrafficJamReq) (*e2e.TrafficJamResp, error) {
	return r.Service.TrafficJam(ctx, req)
}

func (r *queryResolver) GetPainters(ctx context.Context) (*e2e.PaintersResp, error) {
	return r.Service.GetPainters(ctx, nil)
}

func (r *queryResolver) Translate(ctx context.Context, req *e2e.TranslateReq) (*e2e.TranslateResp, error) {
	return r.Service.Translate(ctx, req)
}

type translateRespResolver struct{ *Resolver }

func (r *translateRespResolver) Translations(ctx context.Context, obj *e2e.TranslateResp) (Translations, error) {
	return obj.GetTranslations(), nil
}
