// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package twirpql

import (
	"context"
	"net/http"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/extension"
	"github.com/99designs/gqlgen/graphql/handler/transport"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/twitchtv/twirp"
	"github.com/twitchtv/twirp/ctxsetters"
	"marwan.io/protoc-gen-twirpql/e2e"
)

// Playground is a proxy to github.com/99designs/gqlgen/handler.Playground
// All you need to do is provide a title and the URL Path to the GraphQL handler
func Playground(title, endpoint string) http.Handler {
	return playground.Handler(title, endpoint)
}

// Handler returns a handler to the GraphQL API.
// Server Hooks are optional but if present, they will
// be injected as GraphQL middleware.
func Handler(service e2e.Service, hooks *twirp.ServerHooks) *handler.Server {
	es := NewExecutableSchema(Config{Resolvers: &Resolver{service}})
	srv := handler.New(es)
	srv.AddTransport(transport.POST{})
	srv.Use(extension.Introspection{})
	if hooks == nil {
		return srv
	}
	srv.AroundFields(func(ctx context.Context, next graphql.Resolver) (res interface{}, err error) {
		f := graphql.GetFieldContext(ctx)
		parent := f.Parent.Path().String()
		if parent != "" {
			return next(ctx)
		}
		ctx = ctxsetters.WithMethodName(ctx, f.Field.Name)
		if hooks.RequestRouted != nil {
			ctx, err = hooks.RequestRouted(ctx)
			if err != nil {
				if terr, ok := err.(twirp.Error); ok && hooks.Error != nil {
					ctx = hooks.Error(ctx, terr)
				}
				return nil, err
			}
		}
		res, err = next(ctx)
		if terr, ok := err.(twirp.Error); ok && hooks.Error != nil {
			ctx = hooks.Error(ctx, terr)
		}
		return res, err
	})
	return srv
}
